# File: config.yaml
# Purpose: Configuration file specifying project settings and paths.

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation  # Root directory for data validation artifacts.
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv  # Directory path of the data file for validation.
  STATUS_FILE: artifacts/data_validation/status.txt  # Path to the status file for recording validation status.


data_transformation:
  root_dir: artifacts/data_transformation  # Root directory for data transformation artifacts.
  data_path: artifacts/data_ingestion/winequality-red.csv  # Path to the input data file for transformation.


model_trainer:
  root_dir: artifacts/model_trainer  # Root directory for model training artifacts.
  train_data_path: artifacts/data_transformation/train.csv  # Path to the training data CSV file.
  test_data_path: artifacts/data_transformation/test.csv  # Path to the test data CSV file.
  model_name: model.joblib  # File name for saving the trained machine learning model.
